language: java
# remove line "dist: trusty" once oraclejdk8 is no longer required
dist: trusty
jdk:
- oraclejdk8
sudo: false
notifications:
  slack:
    secure: Gw1wflNIuPalN68ZxElxdtCY2OcuovOr1oodyWemV5nDeCVYEI97ijjIECwpeYQq1W3/DQegoc3F+KeQTgCi50jZluvGOQ1JqW5IVIkmG4eIwlMUjhW0bOQtpUK6lxOEEsdmsCm9A0C/XWATeiDHW72W/fcLz/zGy39ufFrLVBU=
