branch-defaults:
  master:
    environment: mooseheadprod
environment-defaults:
  moosehead-prod:
    branch: null
    repository: null
global:
  application_name: moosehead
  default_ec2_keyname: javabin
  default_region: eu-central-1
  profile: javabin
  sc: git
deploy:
  artifact: app.zip